version: '3'

services:
  postgres-db-test:
    container_name: postgres-db-test
    image: postgres:13
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      DB_NAME: test
      DB_USER: admin
      DB_PASSWORD: admin_password
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - database-data-test:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  pgadmin-test:
    container_name: pgadmin-test
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-data-test:/var/lib/pgadmin
    ports:
      - "5050:80"

  backend-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db-test
      - pgadmin-test
    volumes:
      - .:/usr/app
    env_file:
      - .env

volumes:
  database-data-test:
  pgadmin-data-test: